baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '来啦'
theme = 'anatole'

[params]
title = "I'm Jane Doe"
author = "Qiu"
description = "Call me Jane"
profilePicture = "images/profile.png"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "文章"
  weight = 200
  identifier = "posts"
  url = "/post/"

#  [[menu.main]]
#  name = "About"
#  weight = 300
#  identifier = "about"
#  url = "/about/"
